<?php

/**
 * Created by PhpStorm.
 * User: xpwu
 * Date: 2018/1/1
 * Time: 下午5:00
 */
class ProjectInit {
  static public function init () {
    // TODO: add project init
  }

  static public $_3rdClassLoader= [
    // TODO: third party class
    // "OtherClass"=>\Config\ThirdParty::file1
  ];

  static public $_3rdRequireOnce = [
    // TODO: third party files
    // \Config\ThirdParty::file2
  ];
}