<?php


namespace Tiny\CLI;


use Tiny\CLI;

class CreateIndex extends CLI {

  /**
   * @param array $argv . argv[0] -> first argv
   */
  protected function run(array $argv): void {
    // TODO: Implement run() method.
  }

  /**
   * php cli.phar <cmd> -h 的返回
   * @return string
   */
  function getHelp(): string {
    // TODO: Implement getHelp() method.
  }

  function listInfo(): string {
    // TODO: Implement listInfo() method.
  }
}